import { PromptTemplate } from "./promptTemplateTypes";

export const BUILTIN_PROMPT_TEMPLATES: ReadonlyArray<PromptTemplate> = Object.freeze([
  {
    id: "builtin_general",
    name: "General Code Review",
    description: "Balanced evaluation covering correctness, complexity, readability, and best practices.",
    prompt: "Provide a balanced code review focusing on correctness, time and space complexity, readability, naming conventions, and idiomatic language practices.",
    isBuiltin: true,
    isDefault: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "builtin_cp",
    name: "Competitive Programming",
    description: "Strict focus on worst-case execution speed, bitwise tricks, and fast I/O optimizations.",
    prompt: "Evaluate this solution under strict competitive programming constraints. Prioritize micro-optimizations, constant factor reduction, extreme input bounds (N >= 10^5), memory limits, and potential TLE/MLE risks.",
    isBuiltin: true,
    isDefault: false,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "builtin_google",
    name: "Google Interview",
    description: "Rigorously audit edge cases, trade-offs, scalability, and clear code organization suitable for Big-Tech interviews.",
    prompt: "Review this code as a Senior Technical Interviewer at a Tier-1 tech company. Audit trade-offs between iterative vs recursive approaches, defensive programming, explicit variable naming, and how clearly the algorithm communicates its intent.",
    isBuiltin: true,
    isDefault: false,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "builtin_perf",
    name: "Performance Optimization",
    description: "Deep dive into cache locality, algorithmic bottleneck elimination, and reducing auxiliary space overhead.",
    prompt: "Focus heavily on performance bottlenecks. Identify unnecessary memory allocations, redundant iterations, sub-optimal data structures, and opportunities to convert auxiliary space usage into in-place operations.",
    isBuiltin: true,
    isDefault: false,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "builtin_bugs",
    name: "Bug Detection",
    description: "Laser focus on off-by-one errors, null pointers, integer overflow, and edge cases.",
    prompt: "Act as an automated bug finder and security auditor. Scan specifically for off-by-one errors, null pointer dereferences, integer overflow risks, stack overflow risks with deep recursion, unhandled empty inputs, and boundary condition failures.",
    isBuiltin: true,
    isDefault: false,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "builtin_clean",
    name: "Clean Code",
    description: "Refactor for maintainability, DRY principles, single responsibility, and elegant structure.",
    prompt: "Evaluate code cleanliness and software engineering patterns. Suggest refactoring to improve modularity, eliminate magic numbers, adhere to Single Responsibility Principle (SRP), and write self-documenting code.",
    isBuiltin: true,
    isDefault: false,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "builtin_beginner",
    name: "Explain Like Beginner",
    description: "Simple analogies, plain-English breakdown of complex logic, and encouraging step-by-step guidance.",
    prompt: "Explain the review feedback using beginner-friendly language and intuitive real-world analogies. Break down complex algorithms into simple step-by-step concepts and highlight foundational DSA patterns to learn.",
    isBuiltin: true,
    isDefault: false,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
]);
