import { SkillNode, DependencyEdge, GRAPH_VERSION } from "./learningGraphTypes";

// ─── Deterministic Curated Skill Nodes ────────────────────────────────────────

export const INITIAL_SKILL_NODES: SkillNode[] = [
  // Tier 1: Core Fundamentals
  {
    id: "complexity_analysis",
    name: "Complexity Analysis (Big-O)",
    slug: "complexity-analysis",
    category: "fundamentals",
    type: "technique",
    difficulty: "Easy",
    description: "Deriving worst-case, average-case time and auxiliary space bounds for iterative and recursive procedures.",
    prerequisites: [],
    dependents: ["arrays", "recursion", "sorting"],
    patterns: ["Asymptotic Bounds", "Space Complexity Analysis"],
    masteryScore: 85,
    confidenceScore: 90,
    evidenceCount: 12,
    status: "MASTERED",
    decayFactor: 0.05,
    recentAccuracy: 95,
    solvedProblemsCount: 15,
    difficultyReached: "Medium",
    targetProblemIds: [1, 704],
    position: { x: 450, y: 50 },
  },
  {
    id: "arrays",
    name: "Arrays & Iteration",
    slug: "arrays",
    category: "fundamentals",
    type: "topic",
    difficulty: "Easy",
    description: "Contiguous memory manipulation, indexing math, dynamic sizing, and in-place transformations.",
    prerequisites: ["complexity_analysis"],
    dependents: ["hashing", "two_pointers", "prefix_sum", "sorting"],
    patterns: ["In-Place Modification", "Dynamic Arrays", "Index Mapping"],
    masteryScore: 90,
    confidenceScore: 92,
    evidenceCount: 24,
    status: "MASTERED",
    decayFactor: 0.02,
    recentAccuracy: 92,
    solvedProblemsCount: 22,
    difficultyReached: "Hard",
    targetProblemIds: [1, 121, 53],
    position: { x: 250, y: 150 },
  },
  {
    id: "strings",
    name: "Strings & Character Matching",
    slug: "strings",
    category: "fundamentals",
    type: "topic",
    difficulty: "Easy",
    description: "Immutable and mutable character buffer operations, palindrome checks, and frequency arrays.",
    prerequisites: ["complexity_analysis"],
    dependents: ["two_pointers", "hashing", "tries"],
    patterns: ["Character Frequency Array", "Palindrome Verification", "ASCII Offsets"],
    masteryScore: 88,
    confidenceScore: 85,
    evidenceCount: 18,
    status: "MASTERED",
    decayFactor: 0.04,
    recentAccuracy: 88,
    solvedProblemsCount: 16,
    difficultyReached: "Medium",
    targetProblemIds: [125, 242, 20],
    position: { x: 650, y: 150 },
  },

  // Tier 2: Linear Data Structures & Indexing Techniques
  {
    id: "hashing",
    name: "Hash Maps & Hash Sets",
    slug: "hashing",
    category: "data_structures",
    type: "topic",
    difficulty: "Easy",
    description: "O(1) average lookup, key-value mappings, frequency counters, and complement pair matching.",
    prerequisites: ["arrays"],
    dependents: ["two_pointers", "sliding_window", "prefix_sum", "graphs"],
    patterns: ["Complement Lookup", "Frequency Counter", "Duplicate Detection"],
    masteryScore: 82,
    confidenceScore: 85,
    evidenceCount: 16,
    status: "MASTERED",
    decayFactor: 0.03,
    recentAccuracy: 90,
    solvedProblemsCount: 14,
    difficultyReached: "Medium",
    targetProblemIds: [1, 217, 49],
    position: { x: 150, y: 270 },
  },
  {
    id: "two_pointers",
    name: "Two Pointers",
    slug: "two-pointers",
    category: "fundamentals",
    type: "pattern",
    difficulty: "Easy",
    description: "Opposite-end and same-direction pointer movement on sorted sequences to eliminate nested loops.",
    prerequisites: ["arrays"],
    dependents: ["sliding_window", "intervals", "linked_lists", "binary_search"],
    patterns: ["Opposite-End Collision", "Fast and Slow Pointers", "Partition Pointers"],
    masteryScore: 80,
    confidenceScore: 82,
    evidenceCount: 14,
    status: "MASTERED",
    decayFactor: 0.05,
    recentAccuracy: 85,
    solvedProblemsCount: 12,
    difficultyReached: "Medium",
    targetProblemIds: [167, 11, 15],
    position: { x: 350, y: 270 },
  },
  {
    id: "prefix_sum",
    name: "Prefix Sum & Running Differences",
    slug: "prefix-sum",
    category: "fundamentals",
    type: "pattern",
    difficulty: "Easy",
    description: "Precalculating cumulative sums to answer range query problems in O(1) time.",
    prerequisites: ["arrays", "hashing"],
    dependents: ["sliding_window", "dp_1d"],
    patterns: ["Range Sum Query", "Subarray Sum Equals K", "2D Prefix Sum Matrix"],
    masteryScore: 65,
    confidenceScore: 70,
    evidenceCount: 8,
    status: "DEVELOPING",
    decayFactor: 0.08,
    recentAccuracy: 75,
    solvedProblemsCount: 7,
    difficultyReached: "Medium",
    targetProblemIds: [560, 303],
    position: { x: 550, y: 270 },
  },
  {
    id: "sorting",
    name: "Sorting Algorithms & Custom Comparators",
    slug: "sorting",
    category: "fundamentals",
    type: "topic",
    difficulty: "Easy",
    description: "QuickSort, MergeSort principles, stable sorting, and custom comparator ordering.",
    prerequisites: ["arrays", "complexity_analysis"],
    dependents: ["binary_search", "intervals", "greedy", "heaps"],
    patterns: ["Custom Struct Comparator", "In-Place QuickSelect", "Counting Sort"],
    masteryScore: 78,
    confidenceScore: 80,
    evidenceCount: 10,
    status: "MASTERED",
    decayFactor: 0.05,
    recentAccuracy: 85,
    solvedProblemsCount: 9,
    difficultyReached: "Medium",
    targetProblemIds: [912, 56],
    position: { x: 750, y: 270 },
  },

  // Tier 3: Intermediate Core Techniques
  {
    id: "sliding_window",
    name: "Sliding Window",
    slug: "sliding-window",
    category: "fundamentals",
    type: "pattern",
    difficulty: "Medium",
    description: "Dynamic and fixed-size contiguous subarrays maintaining valid state invariants in O(N) time.",
    prerequisites: ["two_pointers", "hashing"],
    dependents: ["monotonic_stack", "dp_1d"],
    patterns: ["Fixed Size Window", "Dynamic Expanding/Shrinking Window", "Auxiliary Frequency Table"],
    masteryScore: 48,
    confidenceScore: 50,
    evidenceCount: 6,
    status: "LEARNING",
    decayFactor: 0.15,
    recentAccuracy: 60,
    solvedProblemsCount: 5,
    difficultyReached: "Medium",
    targetProblemIds: [3, 424, 76],
    position: { x: 200, y: 400 },
  },
  {
    id: "binary_search",
    name: "Binary Search & Search on Answer",
    slug: "binary-search",
    category: "fundamentals",
    type: "topic",
    difficulty: "Medium",
    description: "Logarithmic search over sorted monotonic spaces and feasibility functions f(x).",
    prerequisites: ["arrays", "sorting"],
    dependents: ["bst", "greedy", "intervals"],
    patterns: ["Exact Value Match", "First True / Boundary Search", "Binary Search on Answer Range"],
    masteryScore: 72,
    confidenceScore: 75,
    evidenceCount: 11,
    status: "DEVELOPING",
    decayFactor: 0.06,
    recentAccuracy: 80,
    solvedProblemsCount: 10,
    difficultyReached: "Medium",
    targetProblemIds: [704, 33, 153, 875],
    position: { x: 450, y: 400 },
  },
  {
    id: "intervals",
    name: "Intervals & Overlap Scheduling",
    slug: "intervals",
    category: "fundamentals",
    type: "pattern",
    difficulty: "Medium",
    description: "Sorting intervals by start or end times to merge ranges, find intersections, and solve room allocation.",
    prerequisites: ["sorting", "two_pointers"],
    dependents: ["greedy"],
    patterns: ["Merge Overlapping Intervals", "Insert Interval", "Sweep-Line Active Interval Count"],
    masteryScore: 70,
    confidenceScore: 72,
    evidenceCount: 9,
    status: "DEVELOPING",
    decayFactor: 0.05,
    recentAccuracy: 78,
    solvedProblemsCount: 8,
    difficultyReached: "Medium",
    targetProblemIds: [56, 57, 435],
    position: { x: 700, y: 400 },
  },

  // Tier 4: Linear & Pointer Data Structures
  {
    id: "linked_lists",
    name: "Linked Lists",
    slug: "linked-lists",
    category: "data_structures",
    type: "topic",
    difficulty: "Medium",
    description: "Singly and doubly linked pointer structures, dummy nodes, reversals, and cycle detection.",
    prerequisites: ["arrays", "two_pointers"],
    dependents: ["trees", "stacks"],
    patterns: ["Sentinel / Dummy Head", "Fast & Slow Floyd Cycle", "In-Place Sublist Reversal"],
    masteryScore: 74,
    confidenceScore: 75,
    evidenceCount: 10,
    status: "DEVELOPING",
    decayFactor: 0.04,
    recentAccuracy: 80,
    solvedProblemsCount: 9,
    difficultyReached: "Medium",
    targetProblemIds: [206, 141, 21, 143],
    position: { x: 100, y: 530 },
  },
  {
    id: "stacks",
    name: "Stacks & Parentheses Matching",
    slug: "stacks",
    category: "data_structures",
    type: "topic",
    difficulty: "Easy",
    description: "Last-In First-Out (LIFO) tracking for nested hierarchies, expressions, and depth traversal.",
    prerequisites: ["arrays"],
    dependents: ["monotonic_stack", "dfs", "recursion"],
    patterns: ["Matching Brackets", "Expression Evaluation", "Auxiliary Min Stack"],
    masteryScore: 84,
    confidenceScore: 86,
    evidenceCount: 12,
    status: "MASTERED",
    decayFactor: 0.03,
    recentAccuracy: 90,
    solvedProblemsCount: 11,
    difficultyReached: "Medium",
    targetProblemIds: [20, 155, 739],
    position: { x: 300, y: 530 },
  },
  {
    id: "monotonic_stack",
    name: "Monotonic Stack & Queue",
    slug: "monotonic-stack",
    category: "advanced_structures",
    type: "pattern",
    difficulty: "Medium",
    description: "Maintaining strictly increasing/decreasing order to find Next Greater Element in O(N).",
    prerequisites: ["stacks", "sliding_window"],
    dependents: ["dp_1d"],
    patterns: ["Next Greater Element", "Largest Rectangle in Histogram", "Sliding Window Maximum Deque"],
    masteryScore: 40,
    confidenceScore: 45,
    evidenceCount: 5,
    status: "LEARNING",
    decayFactor: 0.12,
    recentAccuracy: 55,
    solvedProblemsCount: 4,
    difficultyReached: "Hard",
    targetProblemIds: [739, 84, 239],
    position: { x: 500, y: 530 },
  },
  {
    id: "queues",
    name: "Queues & Breadth-First FIFO",
    slug: "queues",
    category: "data_structures",
    type: "topic",
    difficulty: "Easy",
    description: "FIFO buffer management, circular ring buffers, and level-order traversal roots.",
    prerequisites: ["arrays"],
    dependents: ["bfs", "trees"],
    patterns: ["FIFO Level Buffer", "Circular Queue Pointer", "Double-Ended Deque"],
    masteryScore: 80,
    confidenceScore: 82,
    evidenceCount: 9,
    status: "MASTERED",
    decayFactor: 0.04,
    recentAccuracy: 88,
    solvedProblemsCount: 8,
    difficultyReached: "Medium",
    targetProblemIds: [225, 232],
    position: { x: 750, y: 530 },
  },

  // Tier 5: Trees, Recursion & Search Spaces
  {
    id: "recursion",
    name: "Recursion & Call Stack",
    slug: "recursion",
    category: "fundamentals",
    type: "topic",
    difficulty: "Easy",
    description: "Base case definition, recurrence relation branching, and call stack unwinding.",
    prerequisites: ["complexity_analysis"],
    dependents: ["trees", "backtracking", "dp_1d", "dfs"],
    patterns: ["Base Case Invariant", "Divide & Conquer", "Recursive State Accumulator"],
    masteryScore: 80,
    confidenceScore: 82,
    evidenceCount: 14,
    status: "MASTERED",
    decayFactor: 0.04,
    recentAccuracy: 85,
    solvedProblemsCount: 12,
    difficultyReached: "Medium",
    targetProblemIds: [70, 509],
    position: { x: 450, y: 660 },
  },
  {
    id: "trees",
    name: "Binary Trees & Traversals",
    slug: "trees",
    category: "data_structures",
    type: "topic",
    difficulty: "Medium",
    description: "Hierarchical parent-child nodes, Pre/In/Post-order recursive and level-order iterative traversals.",
    prerequisites: ["recursion", "queues"],
    dependents: ["bst", "dfs", "bfs", "tries"],
    patterns: ["Depth First Tree Traversal", "Level Order BFS", "Lowest Common Ancestor"],
    masteryScore: 68,
    confidenceScore: 70,
    evidenceCount: 10,
    status: "DEVELOPING",
    decayFactor: 0.08,
    recentAccuracy: 75,
    solvedProblemsCount: 9,
    difficultyReached: "Medium",
    targetProblemIds: [104, 226, 102, 236],
    position: { x: 250, y: 780 },
  },
  {
    id: "bst",
    name: "Binary Search Trees (BST)",
    slug: "bst",
    category: "data_structures",
    type: "topic",
    difficulty: "Medium",
    description: "Sorted tree invariant (left < root < right), in-order sorting, range validation, and balanced rotation basics.",
    prerequisites: ["trees", "binary_search"],
    dependents: ["heaps"],
    patterns: ["In-Order Sorted Sequence", "BST Validation with Min/Max Range", "BST Insertion/Deletion"],
    masteryScore: 62,
    confidenceScore: 65,
    evidenceCount: 7,
    status: "DEVELOPING",
    decayFactor: 0.09,
    recentAccuracy: 70,
    solvedProblemsCount: 6,
    difficultyReached: "Medium",
    targetProblemIds: [98, 230, 235],
    position: { x: 500, y: 780 },
  },
  {
    id: "backtracking",
    name: "Backtracking & State Exploration",
    slug: "backtracking",
    category: "algorithmic_paradigms",
    type: "pattern",
    difficulty: "Medium",
    description: "Depth-first combinatorial search (subsets, permutations, combinations) with explicit choose-explore-unchoose state rollback.",
    prerequisites: ["recursion"],
    dependents: ["dfs", "dp_1d"],
    patterns: ["Subset / Power Set Generation", "Permutations with Visited Set", "Pruned Constraint Search (N-Queens/Sudoku)"],
    masteryScore: 52,
    confidenceScore: 55,
    evidenceCount: 8,
    status: "DEVELOPING",
    decayFactor: 0.12,
    recentAccuracy: 65,
    solvedProblemsCount: 7,
    difficultyReached: "Medium",
    targetProblemIds: [78, 46, 39, 51],
    position: { x: 750, y: 780 },
  },

  // Tier 6: Heaps, Greedy & Graphs
  {
    id: "heaps",
    name: "Heaps & Priority Queues",
    slug: "heaps",
    category: "data_structures",
    type: "topic",
    difficulty: "Medium",
    description: "Binary heaps, min/max heap invariant, O(log N) push/pop, and top-K streaming element retrieval.",
    prerequisites: ["trees", "sorting"],
    dependents: ["greedy", "shortest_path"],
    patterns: ["Top-K Frequent Elements", "Kth Largest Element", "Two Heaps for Running Median"],
    masteryScore: 60,
    confidenceScore: 62,
    evidenceCount: 7,
    status: "DEVELOPING",
    decayFactor: 0.09,
    recentAccuracy: 70,
    solvedProblemsCount: 6,
    difficultyReached: "Medium",
    targetProblemIds: [215, 347, 295],
    position: { x: 150, y: 910 },
  },
  {
    id: "greedy",
    name: "Greedy Algorithms",
    slug: "greedy",
    category: "algorithmic_paradigms",
    type: "topic",
    difficulty: "Medium",
    description: "Locally optimal choice heuristics that guarantee global optimality for matroid and interval problems.",
    prerequisites: ["sorting", "intervals", "heaps"],
    dependents: ["shortest_path", "dp_1d"],
    patterns: ["Earliest Deadline First", "Greedy Jump Game", "Gas Station Fuel Balance"],
    masteryScore: 58,
    confidenceScore: 60,
    evidenceCount: 7,
    status: "DEVELOPING",
    decayFactor: 0.10,
    recentAccuracy: 68,
    solvedProblemsCount: 6,
    difficultyReached: "Medium",
    targetProblemIds: [55, 45, 134],
    position: { x: 400, y: 910 },
  },
  {
    id: "graphs",
    name: "Graph Foundations & Representations",
    slug: "graphs",
    category: "data_structures",
    type: "topic",
    difficulty: "Medium",
    description: "Adjacency list, adjacency matrix, edge lists, degree counting, and connectivity basics.",
    prerequisites: ["trees", "hashing"],
    dependents: ["bfs", "dfs", "topological_sort", "union_find", "shortest_path"],
    patterns: ["Adjacency List Construction", "Grid-as-Graph Neighbor Mapping", "Visited Set Invariant"],
    masteryScore: 50,
    confidenceScore: 52,
    evidenceCount: 6,
    status: "LEARNING",
    decayFactor: 0.14,
    recentAccuracy: 60,
    solvedProblemsCount: 5,
    difficultyReached: "Medium",
    targetProblemIds: [200, 133],
    position: { x: 700, y: 910 },
  },

  // Tier 7: Graph Traversals & Advanced Graph Algorithms
  {
    id: "bfs",
    name: "Breadth-First Search (BFS)",
    slug: "bfs",
    category: "algorithmic_paradigms",
    type: "pattern",
    difficulty: "Medium",
    description: "Queue-driven shortest path in unweighted graphs, multi-source simultaneous expansion, and word ladders.",
    prerequisites: ["graphs", "queues"],
    dependents: ["topological_sort", "shortest_path"],
    patterns: ["Shortest Path in Unweighted Grid", "Multi-Source BFS Expansion", "Level-by-Level Step Count"],
    masteryScore: 55,
    confidenceScore: 58,
    evidenceCount: 7,
    status: "DEVELOPING",
    decayFactor: 0.11,
    recentAccuracy: 65,
    solvedProblemsCount: 6,
    difficultyReached: "Medium",
    targetProblemIds: [200, 994, 127],
    position: { x: 150, y: 1040 },
  },
  {
    id: "dfs",
    name: "Depth-First Search (DFS)",
    slug: "dfs",
    category: "algorithmic_paradigms",
    type: "pattern",
    difficulty: "Medium",
    description: "Recursive branch exploration, connected components discovery, cycle detection in directed/undirected graphs.",
    prerequisites: ["graphs", "recursion", "stacks"],
    dependents: ["topological_sort", "dp_2d"],
    patterns: ["Connected Component Flood Fill", "Cycle Detection (3-Color State)", "Bipartite Graph Check"],
    masteryScore: 58,
    confidenceScore: 60,
    evidenceCount: 8,
    status: "DEVELOPING",
    decayFactor: 0.10,
    recentAccuracy: 68,
    solvedProblemsCount: 7,
    difficultyReached: "Medium",
    targetProblemIds: [200, 417, 785],
    position: { x: 400, y: 1040 },
  },
  {
    id: "topological_sort",
    name: "Topological Sort (Kahn's & DFS)",
    slug: "topological-sort",
    category: "advanced_structures",
    type: "pattern",
    difficulty: "Medium",
    description: "Linear ordering of Directed Acyclic Graphs (DAG) using in-degree reduction and DFS post-order reversal.",
    prerequisites: ["graphs", "bfs", "dfs"],
    dependents: ["dp_1d"],
    patterns: ["Kahn's In-Degree Queue", "Course Schedule Prerequisite Resolution", "Alien Dictionary Order"],
    masteryScore: 35,
    confidenceScore: 40,
    evidenceCount: 4,
    status: "LEARNING",
    decayFactor: 0.18,
    recentAccuracy: 50,
    solvedProblemsCount: 3,
    difficultyReached: "Medium",
    targetProblemIds: [207, 210, 269],
    position: { x: 650, y: 1040 },
  },
  {
    id: "union_find",
    name: "Union-Find (Disjoint Set Union)",
    slug: "union-find",
    category: "advanced_structures",
    type: "technique",
    difficulty: "Medium",
    description: "Near-O(1) amortized connectivity queries using path compression and union by rank.",
    prerequisites: ["graphs"],
    dependents: ["shortest_path"],
    patterns: ["Path Compression Find", "Union by Rank/Size", "Redundant Connection Detection"],
    masteryScore: 30,
    confidenceScore: 35,
    evidenceCount: 3,
    status: "LEARNING",
    decayFactor: 0.20,
    recentAccuracy: 45,
    solvedProblemsCount: 3,
    difficultyReached: "Medium",
    targetProblemIds: [684, 547, 323],
    position: { x: 850, y: 1040 },
  },

  // Tier 8: Dynamic Programming & Specialized Topics
  {
    id: "dp_1d",
    name: "1D Dynamic Programming",
    slug: "dp-1d",
    category: "algorithmic_paradigms",
    type: "pattern",
    difficulty: "Medium",
    description: "Optimal substructure and overlapping subproblems: Memoization top-down $\\rightarrow$ Tabulation bottom-up with space optimization.",
    prerequisites: ["recursion", "prefix_sum"],
    dependents: ["dp_2d", "knapsack_dp"],
    patterns: ["Fibonacci State Transitions", "House Robber Non-Adjacent Choice", "Coin Change Unbounded Minimum", "Longest Increasing Subsequence"],
    masteryScore: 42,
    confidenceScore: 45,
    evidenceCount: 6,
    status: "LEARNING",
    decayFactor: 0.16,
    recentAccuracy: 55,
    solvedProblemsCount: 5,
    difficultyReached: "Medium",
    targetProblemIds: [70, 198, 322, 300],
    position: { x: 250, y: 1180 },
  },
  {
    id: "dp_2d",
    name: "2D Grid & String DP",
    slug: "dp-2d",
    category: "algorithmic_paradigms",
    type: "pattern",
    difficulty: "Hard",
    description: "Matrix grid path optimization and 2-string alignment algorithms (LCS, Edit Distance).",
    prerequisites: ["dp_1d", "dfs"],
    dependents: ["knapsack_dp"],
    patterns: ["Grid Unique Paths with Obstacles", "Longest Common Subsequence Matrix", "Levenshtein Edit Distance"],
    masteryScore: 25,
    confidenceScore: 30,
    evidenceCount: 3,
    status: "DISCOVERED",
    decayFactor: 0.22,
    recentAccuracy: 40,
    solvedProblemsCount: 2,
    difficultyReached: "Hard",
    targetProblemIds: [62, 1143, 72],
    position: { x: 500, y: 1180 },
  },
  {
    id: "knapsack_dp",
    name: "Knapsack & Subset Sum DP",
    slug: "knapsack-dp",
    category: "algorithmic_paradigms",
    type: "pattern",
    difficulty: "Hard",
    description: "0/1 Knapsack, Unbounded Knapsack, Partition Equal Subset Sum with 1D array space compression.",
    prerequisites: ["dp_1d", "dp_2d"],
    dependents: [],
    patterns: ["0/1 Knapsack Reverse Traversal", "Target Sum + Subset Transformation", "Coin Change II Combinations"],
    masteryScore: 15,
    confidenceScore: 20,
    evidenceCount: 2,
    status: "LOCKED",
    decayFactor: 0.25,
    recentAccuracy: 30,
    solvedProblemsCount: 1,
    difficultyReached: "Hard",
    targetProblemIds: [416, 494, 518],
    position: { x: 750, y: 1180 },
  },
  {
    id: "shortest_path",
    name: "Shortest Path (Dijkstra)",
    slug: "shortest-path",
    category: "advanced_structures",
    type: "technique",
    difficulty: "Hard",
    description: "Weighted graph shortest path using Min-Heap priority queue in O((V+E) log V) time.",
    prerequisites: ["graphs", "heaps", "bfs"],
    dependents: [],
    patterns: ["Dijkstra Priority Queue", "Network Delay Time", "Cheapest Flights Within K Stops"],
    masteryScore: 18,
    confidenceScore: 22,
    evidenceCount: 2,
    status: "LOCKED",
    decayFactor: 0.25,
    recentAccuracy: 35,
    solvedProblemsCount: 1,
    difficultyReached: "Hard",
    targetProblemIds: [743, 787],
    position: { x: 150, y: 1300 },
  },
  {
    id: "tries",
    name: "Tries (Prefix Trees)",
    slug: "tries",
    category: "advanced_structures",
    type: "topic",
    difficulty: "Medium",
    description: "Tree structure storing character branches for O(L) prefix search and autocomplete.",
    prerequisites: ["trees", "strings"],
    dependents: [],
    patterns: ["Trie Node Children Map", "Prefix Autocomplete Search", "Word Search II with Grid DFS"],
    masteryScore: 35,
    confidenceScore: 40,
    evidenceCount: 4,
    status: "LEARNING",
    decayFactor: 0.18,
    recentAccuracy: 50,
    solvedProblemsCount: 3,
    difficultyReached: "Medium",
    targetProblemIds: [208, 211, 212],
    position: { x: 450, y: 1300 },
  },
  {
    id: "bit_manipulation",
    name: "Bit Manipulation & Bitmasks",
    slug: "bit-manipulation",
    category: "fundamentals",
    type: "technique",
    difficulty: "Medium",
    description: "Bitwise XOR, AND, OR, bit shifts, Brian Kernighan's set-bit counting, and compact bitmask state representation.",
    prerequisites: ["complexity_analysis"],
    dependents: [],
    patterns: ["Single Number XOR Cancel", "Bitmask State Subsets", "Counting Bits Popcount"],
    masteryScore: 55,
    confidenceScore: 58,
    evidenceCount: 6,
    status: "DEVELOPING",
    decayFactor: 0.10,
    recentAccuracy: 65,
    solvedProblemsCount: 5,
    difficultyReached: "Medium",
    targetProblemIds: [136, 191, 338],
    position: { x: 750, y: 1300 },
  },
];

// ─── Deterministic Curated Dependency Edges ───────────────────────────────────

export const INITIAL_DEPENDENCY_EDGES: DependencyEdge[] = [
  // Foundations
  { id: "e1", sourceId: "complexity_analysis", targetId: "arrays", type: "prerequisite", strength: 5, description: "Understanding contiguous array access bounds O(1)." },
  { id: "e2", sourceId: "complexity_analysis", targetId: "strings", type: "prerequisite", strength: 4, description: "Understanding character array allocation and copy costs." },
  { id: "e3", sourceId: "complexity_analysis", targetId: "recursion", type: "prerequisite", strength: 5, description: "Call stack frame depth and recurrence analysis." },
  { id: "e4", sourceId: "complexity_analysis", targetId: "sorting", type: "prerequisite", strength: 5, description: "Comparing O(N^2) vs O(N log N) sorting bounds." },

  // Linear Structures & Pointers
  { id: "e5", sourceId: "arrays", targetId: "hashing", type: "prerequisite", strength: 4, description: "Hash map buckets build on indexed array tables." },
  { id: "e6", sourceId: "arrays", targetId: "two_pointers", type: "prerequisite", strength: 5, description: "Two-pointer index manipulation requires solid array index arithmetic." },
  { id: "e7", sourceId: "arrays", targetId: "prefix_sum", type: "prerequisite", strength: 5, description: "Prefix sums accumulate contiguous array slices." },
  { id: "e8", sourceId: "arrays", targetId: "sorting", type: "prerequisite", strength: 4, description: "Sorting acts on contiguous element arrays." },
  { id: "e9", sourceId: "arrays", targetId: "linked_lists", type: "related", strength: 3, description: "Contiguous memory vs pointer node chaining." },
  { id: "e10", sourceId: "arrays", targetId: "stacks", type: "prerequisite", strength: 4, description: "Stacks are typically backed by dynamic arrays." },
  { id: "e11", sourceId: "arrays", targetId: "queues", type: "prerequisite", strength: 4, description: "Circular ring buffers operate on fixed array indices." },

  // Intermediate Techniques
  { id: "e12", sourceId: "two_pointers", targetId: "sliding_window", type: "prerequisite", strength: 5, description: "Sliding window is a dynamic expanding/shrinking two-pointer pattern." },
  { id: "e13", sourceId: "hashing", targetId: "sliding_window", type: "prerequisite", strength: 4, description: "Sliding window frequently relies on hash frequency tables." },
  { id: "e14", sourceId: "sorting", targetId: "binary_search", type: "prerequisite", strength: 5, description: "Binary search requires sorted or monotonic order." },
  { id: "e15", sourceId: "sorting", targetId: "intervals", type: "prerequisite", strength: 5, description: "Interval problems almost always start by sorting by start or end time." },
  { id: "e16", sourceId: "two_pointers", targetId: "intervals", type: "prerequisite", strength: 3, description: "Interval intersection uses two pointers across two lists." },

  // Stacks & Monotonic
  { id: "e17", sourceId: "stacks", targetId: "monotonic_stack", type: "prerequisite", strength: 5, description: "Monotonic stack enforces ordering on top of standard stack pushes/pops." },
  { id: "e18", sourceId: "sliding_window", targetId: "monotonic_stack", type: "related", strength: 3, description: "Sliding window maximum uses monotonic deque." },

  // Recursion & Trees
  { id: "e19", sourceId: "recursion", targetId: "trees", type: "prerequisite", strength: 5, description: "Tree traversals are naturally expressed via recursive calls." },
  { id: "e20", sourceId: "queues", targetId: "trees", type: "prerequisite", strength: 4, description: "Level-order tree traversal requires a FIFO queue." },
  { id: "e21", sourceId: "trees", targetId: "bst", type: "prerequisite", strength: 5, description: "BST extends binary tree with left < root < right invariant." },
  { id: "e22", sourceId: "binary_search", targetId: "bst", type: "prerequisite", strength: 4, description: "BST search mirrors binary search over node keys." },
  { id: "e23", sourceId: "recursion", targetId: "backtracking", type: "prerequisite", strength: 5, description: "Backtracking is depth-first recursion with state rollback." },

  // Heaps & Greedy
  { id: "e24", sourceId: "trees", targetId: "heaps", type: "prerequisite", strength: 4, description: "Binary heap is a complete binary tree satisfying the heap property." },
  { id: "e25", sourceId: "sorting", targetId: "greedy", type: "prerequisite", strength: 4, description: "Greedy choice often sorts items by cost or ratio." },
  { id: "e26", sourceId: "intervals", targetId: "greedy", type: "application", strength: 4, description: "Interval scheduling is a classic greedy problem." },
  { id: "e27", sourceId: "heaps", targetId: "greedy", type: "related", strength: 3, description: "Greedy algorithms maintain active candidates in priority queues." },

  // Graphs
  { id: "e28", sourceId: "trees", targetId: "graphs", type: "prerequisite", strength: 4, description: "A tree is an acyclic connected graph." },
  { id: "e29", sourceId: "hashing", targetId: "graphs", type: "prerequisite", strength: 4, description: "Graph adjacency lists use hash maps for node lookup." },
  { id: "e30", sourceId: "graphs", targetId: "bfs", type: "prerequisite", strength: 5, description: "BFS explores graph level by level." },
  { id: "e31", sourceId: "queues", targetId: "bfs", type: "prerequisite", strength: 5, description: "BFS relies on a FIFO queue to maintain frontier." },
  { id: "e32", sourceId: "graphs", targetId: "dfs", type: "prerequisite", strength: 5, description: "DFS explores graph paths deeply before backtracking." },
  { id: "e33", sourceId: "recursion", targetId: "dfs", type: "prerequisite", strength: 5, description: "DFS is typically implemented recursively." },
  { id: "e34", sourceId: "bfs", targetId: "topological_sort", type: "prerequisite", strength: 4, description: "Kahn's algorithm uses in-degree queue BFS." },
  { id: "e35", sourceId: "dfs", targetId: "topological_sort", type: "prerequisite", strength: 4, description: "DFS post-order traversal yields reverse topological order." },
  { id: "e36", sourceId: "graphs", targetId: "union_find", type: "application", strength: 4, description: "Union-Find detects cycles and connected components in undirected graphs." },

  // Dynamic Programming
  { id: "e37", sourceId: "recursion", targetId: "dp_1d", type: "prerequisite", strength: 5, description: "DP is memoized recursion or bottom-up recurrence." },
  { id: "e38", sourceId: "prefix_sum", targetId: "dp_1d", type: "related", strength: 3, description: "Prefix sums are the simplest form of 1D DP accumulation." },
  { id: "e39", sourceId: "dp_1d", targetId: "dp_2d", type: "prerequisite", strength: 5, description: "2D DP extends 1D state transition logic to matrices." },
  { id: "e40", sourceId: "dp_1d", targetId: "knapsack_dp", type: "prerequisite", strength: 5, description: "Knapsack problems extend 1D/2D DP with item inclusion states." },
  { id: "e41", sourceId: "dp_2d", targetId: "knapsack_dp", type: "prerequisite", strength: 4, description: "0/1 Knapsack is formulated as a (N x W) 2D DP matrix." },

  // Advanced Techniques
  { id: "e42", sourceId: "heaps", targetId: "shortest_path", type: "prerequisite", strength: 5, description: "Dijkstra requires a Min-Heap priority queue for O((V+E) log V)." },
  { id: "e43", sourceId: "bfs", targetId: "shortest_path", type: "prerequisite", strength: 4, description: "Dijkstra is weighted BFS." },
  { id: "e44", sourceId: "strings", targetId: "tries", type: "prerequisite", strength: 4, description: "Tries store character sequences." },
  { id: "e45", sourceId: "trees", targetId: "tries", type: "prerequisite", strength: 4, description: "Tries are 26-ary prefix trees." },
];
