"use client";

import * as React from "react";
import Link from "next/link";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { useAppContext } from "@/context/AppContext";
import {
  MessageSquare,
  Code2,
  Lightbulb,
  ArrowLeft,
  Edit2,
  Trash2,
  Save,
  Sparkles,
  ExternalLink,
  CheckCircle2,
  AlertTriangle,
  BookOpen,
  Loader2
} from "lucide-react";

export default function Review() {
  const {
    selectedReviewProblem,
    selectedLanguage,
    notes,
    updateNote,
    deleteNote,
    generateAiReview,
    aiReviewMap
  } = useAppContext();

  const problem = selectedReviewProblem;
  const problemId = problem?.id || 0;

  // Compute the default solution for the current problem + language
  const defaultSolution = React.useMemo(() => {
    if (!problem) return "";
    return (
      problem.solutions[selectedLanguage] ??
      problem.solutions["TypeScript"] ??
      Object.values(problem.solutions)[0] ??
      `// Write or paste your ${selectedLanguage} solution here`
    );
  }, [problem, selectedLanguage]);

  const [code, setCode] = React.useState(defaultSolution);
  const [problemUrl, setProblemUrl] = React.useState(problem?.url || "");
  const [problemStatement, setProblemStatement] = React.useState("");
  const [isGenerating, setIsGenerating] = React.useState(false);

  // Derived-state pattern: reset code/url synchronously during render when
  // the problem changes, avoiding setState-inside-useEffect lint violations.
  const prevProblemIdRef = React.useRef(problemId);
  if (prevProblemIdRef.current !== problemId) {
    prevProblemIdRef.current = problemId;
    setCode(defaultSolution);
    setProblemUrl(problem?.url || "");
  }

  // Existing AI Review for this problem (if already generated)
  const existingReview = problemId ? aiReviewMap[problemId] : null;

  // Fallback: no problem selected
  if (!problem) {
    return (
      <div className="space-y-8 select-none">
        <div className="flex flex-col gap-2">
          <h1 className="text-3xl font-extrabold text-slate-900 tracking-tight sm:text-4xl">
            AI Review
          </h1>
          <p className="text-slate-500 text-sm sm:text-base max-w-2xl leading-relaxed">
            Deep-dive code evaluations, complexity analysis, and optimization suggestions generated by AI.
          </p>
        </div>
        <Card>
          <CardContent className="py-20 flex flex-col items-center text-center gap-4">
            <div className="w-16 h-16 rounded-2xl bg-sky-50 flex items-center justify-center text-sky-500">
              <MessageSquare className="w-8 h-8" />
            </div>
            <div className="space-y-1.5 max-w-sm">
              <h3 className="text-base font-bold text-slate-800">No Problem Selected</h3>
              <p className="text-sm text-slate-500 leading-relaxed">
                Select a problem from Practice or History to run real AI code evaluation and review.
              </p>
            </div>
            <div className="flex gap-3 mt-2">
              <Link href="/practice">
                <Button variant="primary" size="sm">
                  Browse Practice
                </Button>
              </Link>
              <Link href="/history" passHref legacyBehavior>
                <Button variant="secondary" size="sm">
                  View History
                </Button>
              </Link>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  const currentNote = notes[problemId.toString()] || "";

  const getDifficultyVariant = (difficulty: string) => {
    if (difficulty === "Easy") return "success" as const;
    if (difficulty === "Medium") return "primary" as const;
    return "warning" as const;
  };

  const handleGenerateReview = async () => {
    if (!code.trim()) return;
    setIsGenerating(true);
    try {
      await generateAiReview({
        problemId: problem.id,
        problemTitle: problem.title,
        problemUrl: problemUrl.trim() || problem.url,
        problemStatement: problemStatement.trim(),
        code: code.trim(),
        language: selectedLanguage,
        difficulty: problem.difficulty,
        topics: problem.topics
      });
    } catch (err) {
      console.error("Failed to generate AI review:", err);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSaveNote = (_e: React.FormEvent<HTMLFormElement>) => {
    _e.preventDefault();
    const textarea = document.getElementById(`note-textarea-${problem.id}`) as HTMLTextAreaElement | null;
    if (textarea) {
      updateNote(problem.id, textarea.value);
    }
  };

  const handleDeleteNote = () => {
    deleteNote(problem.id);
  };

  return (
    <div className="space-y-8 select-none">
      {/* Header */}
      <div className="flex flex-col gap-2">
        <div className="flex items-center gap-3 mb-1">
          <Link href="/practice" passHref legacyBehavior>
            <button className="flex items-center gap-1.5 text-xs font-semibold text-slate-400 hover:text-sky-600 transition-colors cursor-pointer">
              <ArrowLeft className="w-3.5 h-3.5" /> Back to Practice
            </button>
          </Link>
        </div>
        <div className="flex flex-wrap items-start gap-3">
          <h1 className="text-3xl font-extrabold text-slate-900 tracking-tight sm:text-4xl flex-1">
            AI Review
          </h1>
          <Badge variant={getDifficultyVariant(problem.difficulty)} className="mt-1.5">
            {problem.difficulty}
          </Badge>
        </div>
        <p className="text-slate-500 text-sm sm:text-base max-w-2xl leading-relaxed">
          AI code evaluation for <span className="font-semibold text-slate-700">{problem.title}</span> in {selectedLanguage}.
        </p>

        {/* Selection Reason banner if present */}
        {problem.selectionReason && (
          <div className="mt-1 p-3 rounded-xl bg-sky-50/60 border border-sky-100/80 text-xs font-medium text-sky-800">
            <span className="font-bold">Why Recommended:</span> {problem.selectionReason}
          </div>
        )}
      </div>

      {/* Review Content Layout */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">

        {/* Left Column: Solution Code & Problem Statement Inputs */}
        <div className="lg:col-span-2 space-y-6">

          {/* Problem Statement & URL Input Card */}
          <Card>
            <CardHeader className="flex flex-row items-center justify-between pb-3">
              <CardTitle className="text-base">Problem Details &amp; Link</CardTitle>
              {problemUrl && (
                <a
                  href={problemUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-1 text-xs font-bold text-sky-600 hover:text-sky-700 hover:underline"
                >
                  <span>Open on {problem.platform === "leetcode" ? "LeetCode" : "Codeforces"}</span>
                  <ExternalLink className="w-3.5 h-3.5" />
                </a>
              )}
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <label className="text-xs font-bold text-slate-500 uppercase tracking-wider block mb-1">
                  Problem URL (Optional)
                </label>
                <input
                  type="url"
                  placeholder="https://leetcode.com/problems/..."
                  value={problemUrl}
                  onChange={(e) => setProblemUrl(e.target.value)}
                  className="w-full px-3.5 py-2 border border-slate-200 rounded-xl text-xs font-medium focus:outline-none focus:ring-2 focus:ring-sky-500/20 bg-slate-50/50"
                />
              </div>

              <div>
                <label className="text-xs font-bold text-slate-500 uppercase tracking-wider block mb-1">
                  Problem Statement / Notes (Optional)
                </label>
                <textarea
                  placeholder="Paste problem statement or specific constraints here..."
                  value={problemStatement}
                  onChange={(e) => setProblemStatement(e.target.value)}
                  rows={2}
                  className="w-full px-3.5 py-2 border border-slate-200 rounded-xl text-xs font-medium focus:outline-none focus:ring-2 focus:ring-sky-500/20 bg-slate-50/50"
                />
              </div>
            </CardContent>
          </Card>

          {/* Submitted Solution Code Editor */}
          <Card>
            <CardHeader className="flex flex-row items-center justify-between pb-3">
              <div className="flex items-center gap-2.5">
                <div className="w-8 h-8 rounded-lg bg-slate-100 flex items-center justify-center">
                  <Code2 className="w-4 h-4 text-slate-500" />
                </div>
                <CardTitle className="text-base">Solution Code</CardTitle>
              </div>
              <div className="flex items-center gap-2">
                <Badge variant="neutral">{selectedLanguage}</Badge>
                <Button
                  variant="primary"
                  size="sm"
                  onClick={handleGenerateReview}
                  disabled={isGenerating || !code.trim()}
                  className="cursor-pointer gap-1.5"
                >
                  {isGenerating ? (
                    <>
                      <Loader2 className="w-3.5 h-3.5 animate-spin" />
                      <span>Analyzing...</span>
                    </>
                  ) : (
                    <>
                      <Sparkles className="w-3.5 h-3.5" />
                      <span>Generate AI Review</span>
                    </>
                  )}
                </Button>
              </div>
            </CardHeader>
            <CardContent>
              <div className="space-y-2">
                <textarea
                  value={code}
                  onChange={(e) => setCode(e.target.value)}
                  placeholder={`// Paste your ${selectedLanguage} solution code here...`}
                  rows={12}
                  className="w-full bg-slate-900 text-slate-200 font-mono text-xs p-4 rounded-xl focus:outline-none focus:ring-2 focus:ring-sky-500/40 shadow-inner resize-y leading-relaxed"
                />
              </div>
            </CardContent>
          </Card>

          {/* Complexity Analysis Card */}
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-base">Complexity Analysis</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-2 gap-4">
                <div className="p-4 rounded-xl bg-sky-50/50 border border-sky-100/60">
                  <p className="text-[10px] font-bold text-sky-600 uppercase tracking-wider mb-1.5">Time Complexity</p>
                  <p className="text-xl font-extrabold text-slate-900 font-mono">
                    {existingReview ? existingReview.timeComplexity : problem.complexity.time}
                  </p>
                </div>
                <div className="p-4 rounded-xl bg-indigo-50/50 border border-indigo-100/60">
                  <p className="text-[10px] font-bold text-indigo-600 uppercase tracking-wider mb-1.5">Space Complexity</p>
                  <p className="text-xl font-extrabold text-slate-900 font-mono">
                    {existingReview ? existingReview.spaceComplexity : problem.complexity.space}
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Right Column: AI Coach Analysis & Feedback */}
        <div className="space-y-6">

          {/* Coach Analysis Card */}
          <Card className="border-sky-100 bg-sky-50/25">
            <CardHeader className="flex flex-row items-center gap-2.5 pb-2">
              <div className="w-8 h-8 rounded-lg bg-sky-100 flex items-center justify-center text-sky-600">
                <MessageSquare className="w-4 h-4" />
              </div>
              <CardTitle className="text-base">AI Coach Evaluation</CardTitle>
            </CardHeader>
            <CardContent className="space-y-5">
              {existingReview ? (
                <>
                  <div className="space-y-1.5">
                    <span className="text-[10px] font-bold text-sky-600 uppercase tracking-wider">Overall Feedback</span>
                    <p className="text-xs text-slate-700 leading-relaxed font-medium">
                      {existingReview.overallFeedback}
                    </p>
                  </div>

                  <div className="w-full h-px bg-sky-100/80" />

                  <div className="space-y-1.5">
                    <span className="text-[10px] font-bold text-sky-600 uppercase tracking-wider">Correctness Analysis</span>
                    <p className="text-xs text-slate-700 leading-relaxed">
                      {existingReview.correctnessAnalysis}
                    </p>
                  </div>
                </>
              ) : (
                <div className="space-y-3">
                  <div className="space-y-2">
                    <span className="text-[10px] font-bold text-sky-600 uppercase tracking-wider">Topics Covered</span>
                    <div className="flex flex-wrap gap-1.5">
                      {problem.topics.map((topic) => (
                        <Badge key={topic} variant="primary" className="text-[10px]">
                          {topic}
                        </Badge>
                      ))}
                    </div>
                  </div>
                  <p className="text-xs text-slate-500 leading-relaxed font-medium">
                    Click <span className="font-bold text-sky-700">&quot;Generate AI Review&quot;</span> above to analyze your solution code logic, complexity, and correctness.
                  </p>
                </div>
              )}
            </CardContent>
          </Card>

          {/* Optimization Suggestions & Edge Cases Card */}
          <Card>
            <CardHeader className="flex flex-row items-center gap-2.5 pb-2">
              <div className="w-8 h-8 rounded-lg bg-amber-50 flex items-center justify-center text-amber-500">
                <Lightbulb className="w-4 h-4" />
              </div>
              <CardTitle className="text-sm">Optimizations &amp; Edge Cases</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              {existingReview ? (
                <>
                  {existingReview.optimizationSuggestions.length > 0 && (
                    <div className="space-y-2">
                      <span className="text-[10px] font-bold text-amber-600 uppercase tracking-wider flex items-center gap-1">
                        <CheckCircle2 className="w-3 h-3" /> Optimizations
                      </span>
                      {existingReview.optimizationSuggestions.map((opt, i) => (
                        <div key={i} className="flex gap-2 items-start text-xs text-slate-600 leading-relaxed">
                          <div className="w-1.5 h-1.5 rounded-full bg-amber-400 shrink-0 mt-1" />
                          <span>{opt}</span>
                        </div>
                      ))}
                    </div>
                  )}

                  {existingReview.edgeCases.length > 0 && (
                    <div className="space-y-2 pt-1 border-t border-slate-100">
                      <span className="text-[10px] font-bold text-red-500 uppercase tracking-wider flex items-center gap-1">
                        <AlertTriangle className="w-3 h-3" /> Edge Cases to Test
                      </span>
                      {existingReview.edgeCases.map((ec, i) => (
                        <div key={i} className="flex gap-2 items-start text-xs text-slate-600 leading-relaxed">
                          <div className="w-1.5 h-1.5 rounded-full bg-red-400 shrink-0 mt-1" />
                          <span>{ec}</span>
                        </div>
                      ))}
                    </div>
                  )}
                </>
              ) : (
                <div className="space-y-2">
                  {problem.takeaways.map((tip, idx) => (
                    <div key={idx} className="flex gap-2.5 items-start text-xs text-slate-600 leading-relaxed">
                      <div className="w-1.5 h-1.5 rounded-full bg-amber-400 shrink-0 mt-1" />
                      <span>{tip}</span>
                    </div>
                  ))}
                </div>
              )}
            </CardContent>
          </Card>

          {/* Learning Tips Card */}
          {existingReview && existingReview.learningTips.length > 0 && (
            <Card className="border-indigo-100 bg-indigo-50/20">
              <CardHeader className="flex flex-row items-center gap-2.5 pb-2">
                <div className="w-8 h-8 rounded-lg bg-indigo-100 flex items-center justify-center text-indigo-600">
                  <BookOpen className="w-4 h-4" />
                </div>
                <CardTitle className="text-sm">Learning Tips</CardTitle>
              </CardHeader>
              <CardContent className="space-y-2">
                {existingReview.learningTips.map((tip, idx) => (
                  <div key={idx} className="flex gap-2.5 items-start text-xs text-slate-600 leading-relaxed">
                    <div className="w-1.5 h-1.5 rounded-full bg-indigo-500 shrink-0 mt-1" />
                    <span>{tip}</span>
                  </div>
                ))}
              </CardContent>
            </Card>
          )}

          {/* Personal Notes Card */}
          <Card className="border-slate-200 bg-slate-50">
            <CardHeader className="flex flex-row items-center justify-between pb-3">
              <div className="flex items-center gap-2.5">
                <div className="w-8 h-8 rounded-lg bg-slate-100 flex items-center justify-center">
                  <Edit2 className="w-4 h-4 text-slate-600" />
                </div>
                <CardTitle className="text-base">Personal Notes</CardTitle>
              </div>
              <div className="flex items-center gap-2">
                {currentNote.trim() ? (
                  <Button
                    variant="secondary"
                    size="sm"
                    onClick={handleDeleteNote}
                  >
                    <Trash2 className="h-4 w-4" /> Delete
                  </Button>
                ) : null}
              </div>
            </CardHeader>
            <CardContent className="space-y-3">
              <form onSubmit={handleSaveNote} className="space-y-2">
                <textarea
                  id={`note-textarea-${problem.id}`}
                  defaultValue={currentNote}
                  placeholder="Add your personal notes, insights, or questions about this problem..."
                  className="w-full min-h-[100px] resize-y border border-slate-200 rounded-xl px-3 py-2 text-slate-900 focus:ring-2 focus:ring-sky-500/20 focus:border-sky-500 bg-white text-xs font-medium"
                  rows={4}
                />
                <Button type="submit" variant="secondary" size="sm" className="w-full cursor-pointer gap-2">
                  <Save className="h-3.5 w-3.5" /> Save Note
                </Button>
              </form>
            </CardContent>
          </Card>

        </div>
      </div>
    </div>
  );
}