import { AlgorithmDefinition, VisualizerAlgorithmId } from "./visualizerTypes";
import { ALGORITHM_PRESETS } from "./visualizerPresets";

export const ALGORITHM_DEFINITIONS: Record<VisualizerAlgorithmId, AlgorithmDefinition> = {
  two_pointers: {
    id: "two_pointers",
    family: "two_pointers",
    title: "Two Pointers (Target Sum)",
    description: "Inward pointer convergence on a sorted array finding pair indices summing to the target in linear O(N) time.",
    timeComplexity: "O(N)",
    spaceComplexity: "O(1)",
    inputType: "number_array",
    hasTargetInput: true,
    requiresSortedInput: true,
    relatedSkillId: "two_pointers",
    relatedPracticeId: 1,
    pseudocode: [
      { lineNumber: 1, code: "function twoSum(arr, target):", indent: 0 },
      { lineNumber: 2, code: "left = 0, right = arr.length - 1", indent: 1 },
      { lineNumber: 3, code: "while left < right:", indent: 1 },
      { lineNumber: 4, code: "currentSum = arr[left] + arr[right]", indent: 2 },
      { lineNumber: 5, code: "if currentSum == target: return [left, right]", indent: 2 },
      { lineNumber: 6, code: "else if currentSum < target: left++", indent: 2 },
      { lineNumber: 7, code: "else: right--", indent: 2 },
      { lineNumber: 8, code: "return NOT_FOUND", indent: 1 },
    ],
    presets: ALGORITHM_PRESETS.two_pointers,
  },

  sliding_window_max_sum: {
    id: "sliding_window_max_sum",
    family: "sliding_window",
    title: "Sliding Window (Max Sum Subarray)",
    description: "Maintains a fixed window of size K, adding the incoming right element and removing the outgoing left element in O(N) time.",
    timeComplexity: "O(N)",
    spaceComplexity: "O(1)",
    inputType: "number_array",
    hasWindowSizeInput: true,
    relatedSkillId: "sliding_window",
    relatedPracticeId: 3,
    pseudocode: [
      { lineNumber: 1, code: "function maxSumSubarray(arr, k):", indent: 0 },
      { lineNumber: 2, code: "currentSum = sum(arr[0..k-1]), maxSum = currentSum", indent: 1 },
      { lineNumber: 3, code: "for right from k to arr.length - 1:", indent: 1 },
      { lineNumber: 4, code: "currentSum += arr[right]", indent: 2 },
      { lineNumber: 5, code: "currentSum -= arr[right - k]", indent: 2 },
      { lineNumber: 6, code: "maxSum = max(maxSum, currentSum)", indent: 2 },
      { lineNumber: 7, code: "return maxSum", indent: 1 },
    ],
    presets: ALGORITHM_PRESETS.sliding_window_max_sum,
  },

  sliding_window_distinct: {
    id: "sliding_window_distinct",
    family: "sliding_window",
    title: "Sliding Window (Longest Distinct Substring)",
    description: "Dynamic sliding window expanding right and contracting left whenever a duplicate character is encountered.",
    timeComplexity: "O(N)",
    spaceComplexity: "O(min(N, Σ))",
    inputType: "string",
    relatedSkillId: "sliding_window",
    relatedPracticeId: 3,
    pseudocode: [
      { lineNumber: 1, code: "function longestDistinct(str):", indent: 0 },
      { lineNumber: 2, code: "charSet = new Set(), left = 0, maxLength = 0", indent: 1 },
      { lineNumber: 3, code: "for right from 0 to str.length - 1:", indent: 1 },
      { lineNumber: 4, code: "while charSet.has(str[right]):", indent: 2 },
      { lineNumber: 5, code: "charSet.delete(str[left]); left++", indent: 3 },
      { lineNumber: 6, code: "charSet.add(str[right])", indent: 2 },
      { lineNumber: 7, code: "maxLength = max(maxLength, right - left + 1)", indent: 2 },
      { lineNumber: 8, code: "return maxLength", indent: 1 },
    ],
    presets: ALGORITHM_PRESETS.sliding_window_distinct,
  },

  binary_search: {
    id: "binary_search",
    family: "binary_search",
    title: "Binary Search",
    description: "Logarithmic halving of a sorted search space by evaluating the midpoint element. Returns the first matching midpoint encountered.",
    timeComplexity: "O(log N)",
    spaceComplexity: "O(1)",
    inputType: "number_array",
    hasTargetInput: true,
    requiresSortedInput: true,
    relatedSkillId: "binary_search",
    relatedPracticeId: 33,
    pseudocode: [
      { lineNumber: 1, code: "function binarySearch(arr, target):", indent: 0 },
      { lineNumber: 2, code: "low = 0, high = arr.length - 1", indent: 1 },
      { lineNumber: 3, code: "while low <= high:", indent: 1 },
      { lineNumber: 4, code: "mid = low + floor((high - low) / 2)", indent: 2 },
      { lineNumber: 5, code: "if arr[mid] == target: return mid", indent: 2 },
      { lineNumber: 6, code: "else if arr[mid] < target: low = mid + 1", indent: 2 },
      { lineNumber: 7, code: "else: high = mid - 1", indent: 2 },
      { lineNumber: 8, code: "return NOT_FOUND", indent: 1 },
    ],
    presets: ALGORITHM_PRESETS.binary_search,
  },

  daily_temperatures: {
    id: "daily_temperatures",
    family: "monotonic_stack",
    title: "Daily Temperatures",
    description: "Monotonic decreasing index stack tracking unresolved past days and calculating wait time until a warmer day.",
    timeComplexity: "O(N)",
    spaceComplexity: "O(N)",
    inputType: "number_array",
    relatedSkillId: "stack",
    relatedPracticeId: 739,
    pseudocode: [
      { lineNumber: 1, code: "function dailyTemperatures(temps):", indent: 0 },
      { lineNumber: 2, code: "stack = [], res = new Array(temps.length).fill(0)", indent: 1 },
      { lineNumber: 3, code: "for i from 0 to temps.length - 1:", indent: 1 },
      { lineNumber: 4, code: "while stack and temps[i] > temps[stack.top]:", indent: 2 },
      { lineNumber: 5, code: "prev = stack.pop()", indent: 3 },
      { lineNumber: 6, code: "res[prev] = i - prev", indent: 3 },
      { lineNumber: 7, code: "stack.push(i)", indent: 2 },
      { lineNumber: 8, code: "return res", indent: 1 },
    ],
    presets: ALGORITHM_PRESETS.daily_temperatures,
  },

  next_greater_element: {
    id: "next_greater_element",
    family: "monotonic_stack",
    title: "Next Greater Element",
    description: "Monotonic stack resolving the first strictly greater element located to the right for each array position in linear time.",
    timeComplexity: "O(N)",
    spaceComplexity: "O(N)",
    inputType: "number_array",
    relatedSkillId: "stack",
    relatedPracticeId: 496,
    pseudocode: [
      { lineNumber: 1, code: "function nextGreaterElement(arr):", indent: 0 },
      { lineNumber: 2, code: "stack = [], res = new Array(arr.length).fill(-1)", indent: 1 },
      { lineNumber: 3, code: "for i from 0 to arr.length - 1:", indent: 1 },
      { lineNumber: 4, code: "while stack and arr[i] > arr[stack.top]:", indent: 2 },
      { lineNumber: 5, code: "prev = stack.pop()", indent: 3 },
      { lineNumber: 6, code: "res[prev] = arr[i]", indent: 3 },
      { lineNumber: 7, code: "stack.push(i)", indent: 2 },
      { lineNumber: 8, code: "return res", indent: 1 },
    ],
    presets: ALGORITHM_PRESETS.next_greater_element,
  },

  bubble_sort: {
    id: "bubble_sort",
    family: "sorting",
    title: "Bubble Sort",
    description: "Iteratively compares and swaps adjacent out-of-order elements, bubbling the maximum to the sorted suffix on each pass.",
    timeComplexity: "O(N^2)",
    spaceComplexity: "O(1)",
    inputType: "number_array",
    relatedSkillId: "sorting",
    pseudocode: [
      { lineNumber: 1, code: "function bubbleSort(arr):", indent: 0 },
      { lineNumber: 2, code: "for i from 0 to arr.length - 2:", indent: 1 },
      { lineNumber: 3, code: "swapped = false", indent: 2 },
      { lineNumber: 4, code: "for j from 0 to arr.length - 2 - i:", indent: 2 },
      { lineNumber: 5, code: "if arr[j] > arr[j+1]: swap(arr[j], arr[j+1]); swapped = true", indent: 3 },
      { lineNumber: 6, code: "if not swapped: break (early exit)", indent: 2 },
      { lineNumber: 7, code: "return arr", indent: 1 },
    ],
    presets: ALGORITHM_PRESETS.bubble_sort,
  },

  selection_sort: {
    id: "selection_sort",
    family: "sorting",
    title: "Selection Sort",
    description: "Repeatedly locates the minimum element in the unsorted suffix and swaps it into the sorted prefix.",
    timeComplexity: "O(N^2)",
    spaceComplexity: "O(1)",
    inputType: "number_array",
    relatedSkillId: "sorting",
    pseudocode: [
      { lineNumber: 1, code: "function selectionSort(arr):", indent: 0 },
      { lineNumber: 2, code: "for i from 0 to arr.length - 2:", indent: 1 },
      { lineNumber: 3, code: "minIdx = i", indent: 2 },
      { lineNumber: 4, code: "for j from i + 1 to arr.length - 1:", indent: 2 },
      { lineNumber: 5, code: "if arr[j] < arr[minIdx]: minIdx = j", indent: 3 },
      { lineNumber: 6, code: "if minIdx != i: swap(arr[i], arr[minIdx])", indent: 2 },
      { lineNumber: 7, code: "return arr", indent: 1 },
    ],
    presets: ALGORITHM_PRESETS.selection_sort,
  },

  merge_sort: {
    id: "merge_sort",
    family: "sorting",
    title: "Merge Sort",
    description: "Deterministic divide-and-conquer algorithm recursively dividing subarrays and merging auxiliary sorted buffers in O(N log N).",
    timeComplexity: "O(N log N)",
    spaceComplexity: "O(N)",
    inputType: "number_array",
    relatedSkillId: "sorting",
    pseudocode: [
      { lineNumber: 1, code: "function mergeSort(arr, left, right):", indent: 0 },
      { lineNumber: 2, code: "if left >= right: return", indent: 1 },
      { lineNumber: 3, code: "mid = left + floor((right - left) / 2)", indent: 1 },
      { lineNumber: 4, code: "mergeSort(arr, left, mid) // left subtree first", indent: 1 },
      { lineNumber: 5, code: "mergeSort(arr, mid + 1, right) // right subtree", indent: 1 },
      { lineNumber: 6, code: "merge(arr, left, mid, right) // auxiliary merge", indent: 1 },
    ],
    presets: ALGORITHM_PRESETS.merge_sort,
  },
};
